use_modular_headers!

platform :ios, '14.0'

target 'VATextureKit_Example' do
  inhibit_all_warnings!
  pod 'VATextureKitSpec', :path => '../'
  pod 'VATextureKit', :path => '../'
  pod 'VATextureKitRx', :path => '../'
  pod 'VATextureKitCombine', :path => '../'
  pod 'Swiftional', '~> 2.0.0'
  pod 'VANavigator', '~> 2.0.0'

  target 'VATextureKit_Tests' do
    inhibit_all_warnings!
    inherit! :search_paths

    pod 'RxTest'
    pod 'RxBlocking'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
    if target.name == "Texture"
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AS_ENABLE_TEXTNODE=1']
      end
    end
    if target.name == "VATextureKitCombine"
      target.build_configurations.each do |config|
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited) -D AS_ENABLE_TEXTNODE2']
        config.build_settings['SWIFT_VERSION'] = '6.0'
        config.build_settings['SWIFT_UPCOMING_FEATURE_EXISTENTIAL_ANY'] = 'YES'
        config.build_settings['SWIFT_UPCOMING_FEATURE_INTERNAL_IMPORTS_BY_DEFAULT'] = 'YES'
        config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'complete'
      end
    end
    if target.name == "VATextureKitRx"
      target.build_configurations.each do |config|
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited) -D AS_ENABLE_TEXTNODE2']
        config.build_settings['SWIFT_VERSION'] = '6.0'
        config.build_settings['SWIFT_UPCOMING_FEATURE_EXISTENTIAL_ANY'] = 'YES'
        config.build_settings['SWIFT_UPCOMING_FEATURE_INTERNAL_IMPORTS_BY_DEFAULT'] = 'YES'
        config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'complete'
      end
    end
    if target.name == "VATextureKit"
      target.build_configurations.each do |config|
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited) -D AS_ENABLE_TEXTNODE2']
        config.build_settings['SWIFT_VERSION'] = '6.0'
        config.build_settings['SWIFT_UPCOMING_FEATURE_EXISTENTIAL_ANY'] = 'YES'
        config.build_settings['SWIFT_UPCOMING_FEATURE_INTERNAL_IMPORTS_BY_DEFAULT'] = 'YES'
        config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'complete'
      end
    end
    if target.name == "VATextureKitSpec"
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '6.0'
        config.build_settings['SWIFT_UPCOMING_FEATURE_EXISTENTIAL_ANY'] = 'YES'
        config.build_settings['SWIFT_UPCOMING_FEATURE_INTERNAL_IMPORTS_BY_DEFAULT'] = 'YES'
        config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'complete'
      end
    end
  end
end
