use_modular_headers!

platform :ios, '11.0'

target 'VATextureKit_Example' do
  inhibit_all_warnings!
  pod 'VATextureKit', :path => '../'
  pod 'VATextureKitRx', :path => '../'
  pod 'Swiftional', '0.3.3'
  pod 'R.swift'

  target 'VATextureKit_Tests' do
    inhibit_all_warnings!
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
    if target.name == "Texture"
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AS_ENABLE_TEXTNODE=1']
      end
    end
    if target.name == "VATextureKit"
      target.build_configurations.each do |config|
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited) -D AS_ENABLE_TEXTNODE2']
      end
    end
  end
end
