use_modular_headers!

platform :ios, '13.0'

def project_pods
  inhibit_all_warnings!

  pod 'VATextureKitSpec', :path => '../'
  pod 'VATextureKit', :path => '../'
  pod 'VATextureKitRx', :path => '../'
  pod 'Swiftional'
  pod 'R.swift'
  pod 'RxSwiftExt'
  pod 'RxKeyboard'
end

def test_pods
  inhibit_all_warnings!
  inherit! :search_paths

  pod 'RxBlocking'
  pod 'RxTest'
end

target 'MoviesExample' do
  project_pods

  target 'MoviesTests' do
    test_pods
  end

  target 'MoviesSnapshotTests' do
    test_pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
    if target.name == "Texture"
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AS_ENABLE_TEXTNODE=1']
      end
    end
    if target.name == "VATextureKit"
      target.build_configurations.each do |config|
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited) -D AS_ENABLE_TEXTNODE2']
      end
    end
  end
end
