use_modular_headers!

platform :ios, '13.0'

def project_pods
  inhibit_all_warnings!

  pod 'VATextureKit', :path => '../'
  pod 'Swiftional', '0.2.5'
  pod 'R.swift'
  pod 'RxSwiftExt'
  pod 'RxKeyboard'
end

def test_pods
  inhibit_all_warnings!
  inherit! :search_paths

  pod 'RxBlocking'
  pod 'RxTest'
end

target 'MoviesExample' do
  project_pods

  target 'MoviesTests' do
    test_pods
  end

  target 'MoviesSnapshotTests' do
    test_pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
